name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        version: 12

    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: Creating Build
      run: npm run build
      
    - name: Installing gh-pages
      run: npm install -g surge gh-pages@2.1.1
      
    - name: Deploying on gh-pages
      run: gh-pages -d ./build
